### ISSUE TITLE
Alternative Download Link for Preprocessed data

### ISSUE THREAD

**Issue by sh0416** [e-bug/volta#14]
Hi.

Could I ask another download link for preprocessed data?
I tried to download conceptual caption, but it takes 3 months for completing download..

Thank you

**Comment by e-bug** [comment]
Hi,

Thanks for reaching out. That sounds horrible :(
That's the only cloud storage I have access to. If you know or have other servers, I'd be happy to push the data there too!

**Comment by sh0416** [comment]
Could you please push your data into the following link?
It could be better if you send it for my email (seonghyeon.drew@gmail.com).
Thank you

https://drive.google.com/drive/folders/1e994iz5S33oDylzMzbQc3siv5G31jmq_?usp=sharing

**Comment by e-bug** [comment]
Uploading them now!

Let me know if you have this space for free -- I could upload all the data there as a mirror for others as well.

**Comment by sh0416** [comment]
I think the owner of the directory is set to you.
You might change the owner of the directory to me to remove the storage limit.
Thank for the fast reply.

**Comment by sh0416** [comment]
FYI, the space is not for free..

**Comment by e-bug** [comment]
Ok, I see. Let's at least allow you to get the data :)

The upload was supposed to be finished, but I found the following error:
`Failed to upload file: googleapi: Error 403: The user's Drive storage quota has been exceeded., storageQuotaExceeded`

The owner of the gDrive is still you. Let me know when you increase the space so I can try again!
