### ISSUE TITLE
vg-gqa_boxes36.lmdb file

### ISSUE THREAD

**Issue by nooralahzadeh** [e-bug/volta#16]
Hi, 
Is it possible to make "vg-gqa_boxes36.lmdb" file available?
It seems the h5 version is available to download! 

Thanks

**Comment by e-bug** [comment]
Hi,

I found that uploading the LMDB files made their size in the order of TBs.
So, I just uploaded the H5 version, and you can quickly convert it to LMDB using [this script](https://github.com/e-bug/volta/blob/main/features_extraction/h5_to_lmdb.py).

Let me know if you have any issues!

**Comment by nooralahzadeh** [comment]
Hi, 
Thanks for the quick reply. The script creates an `lmdb` folder which includes `data.mdb` and `lock.mdb`. Which one I should point to in the task_config file?

**Comment by e-bug** [comment]
Just the lmdb folder :)
