### ISSUE TITLE
Unable to find fine-tuned checkpoints and features

### ISSUE THREAD

**Issue by gchhablani** [e-bug/volta#19]
I am trying to evaluate the vilbert model on flickr30k dataset using the script, but I am not sure where to download the fine-tuned checkpoints from, as well as the features.

Can someone please help me with this?
Thanks!

**Comment by e-bug** [comment]
Hi,

You can find the features for all the datasets [here](https://github.com/e-bug/volta/tree/main/data#preprocessed-data).

We have not released the fine-tuned checkpoints.
