### ISSUE TITLE
LMDB file download

### ISSUE THREAD

**Issue by darthgera123** [e-bug/volta#2]
Currently  to download LMDB files , the link opens up the lmdb file and we download each content separately. Following [this](https://sid.erda.dk/cgi-sid/ls.py?share_id=eEqyrN1IVs;current_dir=resnet101_faster_rcnn_genome_imgfeats/volta;flags=f) link. Can you share a link where we can directly download the lmdb file as we arent able to compress the contents back into lmdb format? @elliottd @e-bug

**Comment by e-bug** [comment]
Hi, I'm not sure I follow what you mean.
As shown [here](https://github.com/e-bug/volta/blob/main/config_tasks/vilbert_test_tasks.yml#L77), you just need to specify a path to the folder ending in `.lmdb`.
So "refcoco+_unc_dets36_feat.lmdb" is not actually a file but a folder. Does this help?

**Comment by darthgera123** [comment]
Thanks for replying. I thought lmdb was a compressed file like zip. Thanks for clearing that up. Also another question, do you have a smaller version of resnet101_faster_rcnn_genome_imgfeats/ for vqa which is 1TB, which as you can imagine is quite unfeasible for downloading as well as storing.

**Comment by e-bug** [comment]
I don't but you can preprocess a subset of the data by following the general [instructions](https://github.com/e-bug/volta/tree/main/data/vqa).
