### ISSUE TITLE
h5 files

### ISSUE THREAD

**Issue by PhehJingJie** [e-bug/volta#20]
"NB: I have noticed that uploading LMDB files made their size grow to the order of TBs. So, instead, I recently uploaded the H5 versions that can quickly be converted to LMDB locally using [this script](https://github.com/e-bug/volta/blob/main/features_extraction/h5_to_lmdb.py)."

Can I check where can I find the h5 files?

**Comment by e-bug** [comment]
Hi, sorry for the late reply -- I was travelling.

You can find H5 files [here](https://github.com/e-bug/volta/tree/main/data#preprocessed-data), when referring to "IGLUE" data.
