### ISSUE TITLE
Generating hard negative captions in Flick30k dataset

### ISSUE THREAD

**Issue by LandyGuo** [e-bug/volta#4]
A download link of hard negative captions is provided for the Flick30k dataset [here](https://github.com/e-bug/volta/blob/main/data/flickr30k/README.md. ).
But neither explanations nor scripts are found for generating those hard negatives.  
Could you help reproduce the generation process?
 @e-bug @elliottd

**Comment by e-bug** [comment]
We have re-used the ones uploaded for [ViLBERT-MT](https://github.com/facebookresearch/vilbert-multi-task).
I believe [this script](https://github.com/e-bug/volta/blob/main/scripts/generate_pool.py) generates them.
Let us know if they match!

**Comment by LandyGuo** [comment]
thanks. Verified that they are exactly match.   closing it now
