### ISSUE TITLE
Finetuning models on SNLI-VE

### ISSUE THREAD

**Issue by jaweriah** [e-bug/volta#7]
Hi, 

To finetune the pre-trained models(ctrl) for the snli-ve dataset, all I need to do is to run the training script in the examples? 
Is my understanding correct? Or there are some other changes that need to be made?

Thanks!

**Comment by e-bug** [comment]
Hi,

Yes, you can look at the [example for ViLBERT](https://github.com/e-bug/volta/tree/main/examples/vilbert/snli_ve).

You can of course specify a different architecture and hyperparameters (see also the ones in the config_tasks).

**Comment by jaweriah** [comment]
Yes, I am following the example of ViLBERT and using that script for other models.

Thanks for your response :)
