### ISSUE TITLE
Is it possible to release pretrained model weights (without downstream task fine-tuned)?

### ISSUE THREAD

**Issue by Mallory24** [e-bug/volta#9]
Hello! Thanks for your great repository.
I saw you only release the already fine-tuned V+L models, is it possible to distribute pretrained model weights only for the 5 models in your controlled set-up?

Thanks in advance!

**Comment by e-bug** [comment]
Hi, 
The currently released weights are actually after pretraining!

The values in the table are the expected performance when you fine-tune them. Sorry for the confusion.

**Comment by Mallory24** [comment]
Hi,
Thanks for the clarification!
